[2025-03-16T17:43:32.841+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Google_map.transform_phase_2_task manual__2025-03-16T16:15:39.596689+00:00 [queued]>
[2025-03-16T17:43:32.852+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Google_map.transform_phase_2_task manual__2025-03-16T16:15:39.596689+00:00 [queued]>
[2025-03-16T17:43:32.852+0000] {taskinstance.py:2170} INFO - Starting attempt 12 of 13
[2025-03-16T17:43:32.868+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): transform_phase_2_task> on 2025-03-16 16:15:39.596689+00:00
[2025-03-16T17:43:32.872+0000] {standard_task_runner.py:60} INFO - Started process 147359 to run task
[2025-03-16T17:43:32.876+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'Google_map', 'transform_phase_2_task', 'manual__2025-03-16T16:15:39.596689+00:00', '--job-id', '134', '--raw', '--subdir', 'DAGS_FOLDER/google_map_dag_etl.py', '--cfg-path', '/tmp/tmphnwd2q6g']
[2025-03-16T17:43:32.878+0000] {standard_task_runner.py:88} INFO - Job 134: Subtask transform_phase_2_task
[2025-03-16T17:43:32.949+0000] {task_command.py:423} INFO - Running <TaskInstance: Google_map.transform_phase_2_task manual__2025-03-16T16:15:39.596689+00:00 [running]> on host DESKTOP-AVAHALM.
[2025-03-16T17:43:33.178+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='master_m2si' AIRFLOW_CTX_DAG_ID='Google_map' AIRFLOW_CTX_TASK_ID='transform_phase_2_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-16T16:15:39.596689+00:00' AIRFLOW_CTX_TRY_NUMBER='12' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-16T16:15:39.596689+00:00'
[2025-03-16T17:49:58.324+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2025-03-16T17:49:58.331+0000] {process_utils.py:131} INFO - Sending 15 to group 147359. PIDs of all processes in the group: [147359]
[2025-03-16T17:49:58.332+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 147359
[2025-03-16T17:50:58.340+0000] {process_utils.py:149} WARNING - process psutil.Process(pid=147359, name='pt_main_thread', status='sleeping', started='17:43:31') did not respond to SIGTERM. Trying SIGKILL
[2025-03-16T17:50:58.343+0000] {process_utils.py:86} INFO - Sending the signal 9 to group 147359
[2025-03-16T17:50:58.439+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=147359, name='pt_main_thread', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='17:43:31') (147359) terminated with exit code -9
[2025-03-16T17:50:58.439+0000] {standard_task_runner.py:175} ERROR - Job 134 was killed before it finished (likely due to running out of memory)
