[2025-03-15T17:23:44.235+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Google_map.insert_data_task manual__2025-03-15T17:23:40.549476+00:00 [queued]>
[2025-03-15T17:23:44.261+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Google_map.insert_data_task manual__2025-03-15T17:23:40.549476+00:00 [queued]>
[2025-03-15T17:23:44.263+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-03-15T17:23:44.287+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): insert_data_task> on 2025-03-15 17:23:40.549476+00:00
[2025-03-15T17:23:44.296+0000] {standard_task_runner.py:60} INFO - Started process 102315 to run task
[2025-03-15T17:23:44.307+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'Google_map', 'insert_data_task', 'manual__2025-03-15T17:23:40.549476+00:00', '--job-id', '86', '--raw', '--subdir', 'DAGS_FOLDER/google_map_dag_etl.py', '--cfg-path', '/tmp/tmp3t7xowy0']
[2025-03-15T17:23:44.311+0000] {standard_task_runner.py:88} INFO - Job 86: Subtask insert_data_task
[2025-03-15T17:23:44.504+0000] {task_command.py:423} INFO - Running <TaskInstance: Google_map.insert_data_task manual__2025-03-15T17:23:40.549476+00:00 [running]> on host DESKTOP-AVAHALM.
[2025-03-15T17:23:44.729+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='master_m2si' AIRFLOW_CTX_DAG_ID='Google_map' AIRFLOW_CTX_TASK_ID='insert_data_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-15T17:23:40.549476+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-15T17:23:40.549476+00:00'
[2025-03-15T17:23:44.752+0000] {logging_mixin.py:188} INFO - ❌ Erreur lors de l'insertion des données : syntax error at or near ")"
LINE 12:         );
                 ^
[2025-03-15T17:23:44.753+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-03-15T17:23:44.784+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=Google_map, task_id=insert_data_task, execution_date=20250315T172340, start_date=20250315T172344, end_date=20250315T172344
[2025-03-15T17:23:44.828+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-15T17:23:44.866+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
