[2025-03-16T15:29:46.717+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Google_map.extract_data_task manual__2025-03-16T15:28:09.434150+00:00 [queued]>
[2025-03-16T15:29:46.735+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Google_map.extract_data_task manual__2025-03-16T15:28:09.434150+00:00 [queued]>
[2025-03-16T15:29:46.736+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 3
[2025-03-16T15:29:46.767+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): extract_data_task> on 2025-03-16 15:28:09.434150+00:00
[2025-03-16T15:29:46.779+0000] {standard_task_runner.py:60} INFO - Started process 60048 to run task
[2025-03-16T15:29:46.785+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'Google_map', 'extract_data_task', 'manual__2025-03-16T15:28:09.434150+00:00', '--job-id', '112', '--raw', '--subdir', 'DAGS_FOLDER/google_map_dag_etl.py', '--cfg-path', '/tmp/tmpq9giujir']
[2025-03-16T15:29:46.788+0000] {standard_task_runner.py:88} INFO - Job 112: Subtask extract_data_task
[2025-03-16T15:29:46.959+0000] {task_command.py:423} INFO - Running <TaskInstance: Google_map.extract_data_task manual__2025-03-16T15:28:09.434150+00:00 [running]> on host DESKTOP-AVAHALM.
[2025-03-16T15:29:47.370+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='master_m2si' AIRFLOW_CTX_DAG_ID='Google_map' AIRFLOW_CTX_TASK_ID='extract_data_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-16T15:28:09.434150+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-16T15:28:09.434150+00:00'
[2025-03-16T15:29:48.020+0000] {logger.py:11} INFO - ====== WebDriver manager ======
[2025-03-16T15:29:48.378+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2025-03-16T15:29:48.788+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2025-03-16T15:29:48.988+0000] {logger.py:11} INFO - Driver [/home/nord/.wdm/drivers/chromedriver/linux64/134.0.6998.88/chromedriver-linux64/chromedriver] found in cache
[2025-03-16T15:29:54.388+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/nord/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/nord/venv/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/nord/venv/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/nord/airflow/dags/google_map_dag_etl.py", line 33, in <lambda>
    python_callable=lambda: __import__('main_scraping_script').main()
  File "/home/nord/airflow/dags/main_scraping_script.py", line 155, in main
    all_data = extract_data(driver, banques)
  File "/home/nord/airflow/dags/main_scraping_script.py", line 127, in extract_data
    bank_data = extract_agency_data(driver, banque, url)
  File "/home/nord/airflow/dags/main_scraping_script.py", line 63, in extract_agency_data
    driver.get(url)
  File "/home/nord/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 393, in get
    self.execute(Command.GET, {"url": url})
  File "/home/nord/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 384, in execute
    self.error_handler.check_response(response)
  File "/home/nord/venv/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: target frame detached
  (failed to check if window was closed: disconnected: Unable to receive message from renderer)
  (Session info: chrome=134.0.6998.88)
Stacktrace:
#0 0x563c58285a1a <unknown>
#1 0x563c57d3d1e3 <unknown>
#2 0x563c57d243f6 <unknown>
#3 0x563c57d23359 <unknown>
#4 0x563c57d4bd50 <unknown>
#5 0x563c57d4b057 <unknown>
#6 0x563c57ddb3ba <unknown>
#7 0x563c57db49a3 <unknown>
#8 0x563c57d8060e <unknown>
#9 0x563c57d81dd1 <unknown>
#10 0x563c5824bddb <unknown>
#11 0x563c5824fcbc <unknown>
#12 0x563c58233392 <unknown>
#13 0x563c58250834 <unknown>
#14 0x563c582171ef <unknown>
#15 0x563c58274038 <unknown>
#16 0x563c58274216 <unknown>
#17 0x563c58284896 <unknown>
#18 0x7fc97d6d2609 start_thread

[2025-03-16T15:29:54.459+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=Google_map, task_id=extract_data_task, execution_date=20250316T152809, start_date=20250316T152946, end_date=20250316T152954
[2025-03-16T15:29:54.517+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 112 for task extract_data_task (Message: target frame detached
  (failed to check if window was closed: disconnected: Unable to receive message from renderer)
  (Session info: chrome=134.0.6998.88)
Stacktrace:
#0 0x563c58285a1a <unknown>
#1 0x563c57d3d1e3 <unknown>
#2 0x563c57d243f6 <unknown>
#3 0x563c57d23359 <unknown>
#4 0x563c57d4bd50 <unknown>
#5 0x563c57d4b057 <unknown>
#6 0x563c57ddb3ba <unknown>
#7 0x563c57db49a3 <unknown>
#8 0x563c57d8060e <unknown>
#9 0x563c57d81dd1 <unknown>
#10 0x563c5824bddb <unknown>
#11 0x563c5824fcbc <unknown>
#12 0x563c58233392 <unknown>
#13 0x563c58250834 <unknown>
#14 0x563c582171ef <unknown>
#15 0x563c58274038 <unknown>
#16 0x563c58274216 <unknown>
#17 0x563c58284896 <unknown>
#18 0x7fc97d6d2609 start_thread
; 60048)
[2025-03-16T15:29:54.573+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-03-16T15:29:54.625+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
